name: App Build

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: |
          if [ "${{matrix.os}}" == "macos-latest" ]; then
            npm run mac
            7z a MacOS.7z "dist/Google Messages-darwin-universal" -r
          else if [ "${{matrix.os}}" == "ubuntu-latest" ]; then
            npm run linux
            7z a Linux.7z "dist/GoogleMessages-linux-x64" -r
          else
            npm run windows
            7za a Windows.7z "dist/Google Messages-win32-x64" -r
          fi
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: "*.7z"
