name: Linux Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run linux
      - run: |
          7z a Linux.7z "dist/GoogleMessages-linux-x64" -r
      - uses: actions/upload-artifact@v3
        with:
          name: Linux App
          path: "*.7z"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          prerelease: True
          name: Development build
          files: "*.7z"
